name: Despliegue a Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v3

      - name: Instalar Surge.sh
        run: npm install --global surge

      - name: Desplegar a Surge.sh
        run: surge --project ./ --domain posteandoweb.surge.sh --token ${{ secrets.SURGE_TOKEN }}